### ISSUE TITLE
Request: add option to enable/disable/add/remove repo from repolist

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/packagekit.dart#18]
Showing the repo list is nice, it would be cool to also manipulate its entries if this is possible. 

Example UI:
![grafik](https://user-images.githubusercontent.com/15329494/174640153-101b4fe5-2a4b-4ae1-a0c0-6dbee59f26d6.png)

**Comment by robert-ancell** [comment]
Looks like there is no method to add repositories (you have to use APT directly for that), but I've added the other methods.

**Comment by Feichtmeier** [comment]
Thanks @robert-ancell !
https://github.com/ubuntu-flutter-community/software/pull/49

https://user-images.githubusercontent.com/15329494/174732990-bb438f6d-58d8-4e2c-947a-e317ddc0c88b.mp4
