### ISSUE TITLE
Installing/removing a deb package locks the PackageKitClient, cannot search for packages until the operation is complete

### ISSUE THREAD

**Issue by oSoMoN** [canonical/packagekit.dart#25]
Initially filed as https://github.com/ubuntu-flutter-community/software/issues/444.

Steps to reproduce, in the [software store app](https://github.com/ubuntu-flutter-community/software) that makes use of packagekit.dart:

   1. search for "0ad-data"
   2. open the result for the deb package with that name (it's a large package, installed size: 3296 MB)
   3. click the "Install" button, installation will take a while, even on a system with fast I/O
   4. click the back button to go back to the search results

Expected result: the results from the previous search are still displayed, and one can issue a new search query.
Actual result: a blank result page with a spinner that doesn't go away until the package is done installing, which on my machine can take ~ 1 minute.

**Comment by robert-ancell** [comment]
This is PackageKit doing this, you can see the same result by running both these commands at the same time:
```
$ pkcon install 0ad-data
$ pkcon refresh
```
If the refresh is started after the install it sits there with the status `Waiting in queue` until the install completes.
